-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-28 15:44:05 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE Cabin CASCADE CONSTRAINTS 
;

DROP TABLE Country CASCADE CONSTRAINTS 
;

DROP TABLE Cruise CASCADE CONSTRAINTS 
;

DROP TABLE Manifest CASCADE CONSTRAINTS 
;

DROP TABLE Operator CASCADE CONSTRAINTS 
;

DROP TABLE Passenger CASCADE CONSTRAINTS 
;

DROP TABLE Port CASCADE CONSTRAINTS 
;

DROP TABLE Ship CASCADE CONSTRAINTS 
;

DROP TABLE Visit CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Cabin 
    ( 
     cabin_number      VARCHAR2 (8)  NOT NULL , 
     ship_code         NUMBER (20)  NOT NULL , 
     sleeping_capacity NUMBER (8)  NOT NULL , 
     cabin_class       VARCHAR2 (10)  NOT NULL 
    ) 
;

ALTER TABLE Cabin 
    ADD CONSTRAINT ship_cabinclass 
    CHECK (cabin_class IN ('B', 'I', 'OV', 'S')) 
;

COMMENT ON COLUMN Cabin.cabin_number IS 'The cabins on a given ship are identified by a cabin number' 
;

COMMENT ON COLUMN Cabin.ship_code IS 'a ship code to identify the ship' 
;

COMMENT ON COLUMN Cabin.sleeping_capacity IS 'a particular cabin''s sleeping capacity' 
;

COMMENT ON COLUMN Cabin.cabin_class IS ' the cabin''s class for a given ship' 
;

ALTER TABLE Cabin 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_number, ship_code ) ;

CREATE TABLE Country 
    ( 
     Country_code CHAR (3)  NOT NULL , 
     Country_name VARCHAR2 (20)  NOT NULL 
    ) 
;

COMMENT ON COLUMN Country.Country_code IS 'country code' 
;

COMMENT ON COLUMN Country.Country_name IS 'country name' 
;

ALTER TABLE Country 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( Country_code ) ;

CREATE TABLE Cruise 
    ( 
     cruise_id      NUMBER (10)  NOT NULL , 
     cruise_name    VARCHAR2 (100)  NOT NULL , 
     description    VARCHAR2 (100)  NOT NULL , 
     departure_date DATE  NOT NULL , 
     departure_time DATE  NOT NULL , 
     cost_perperson NUMBER (10)  NOT NULL , 
     ship_code      NUMBER (20)  NOT NULL 
    ) 
;

COMMENT ON COLUMN Cruise.cruise_id IS 'A cruise ID identifies each such cruise' 
;

COMMENT ON COLUMN Cruise.cruise_name IS 'the name of the cruise' 
;

COMMENT ON COLUMN Cruise.description IS ' a brief description of the cruise' 
;

COMMENT ON COLUMN Cruise.departure_date IS 'departs on a particular date' 
;

COMMENT ON COLUMN Cruise.departure_time IS 'departs at a particular time' 
;

COMMENT ON COLUMN Cruise.cost_perperson IS 'cost per person' 
;

COMMENT ON COLUMN Cruise.ship_code IS 'a ship code to identify the ship' 
;

ALTER TABLE Cruise 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE Manifest 
    ( 
     cruise_id        NUMBER (10)  NOT NULL , 
     passenger_id     VARCHAR2 (20)  NOT NULL , 
     cabin_number     VARCHAR2 (8)  NOT NULL , 
     ship_code        NUMBER (20)  NOT NULL , 
     boarded_datetime DATE  NOT NULL 
    ) 
;

COMMENT ON COLUMN Manifest.cruise_id IS 'A cruise ID identifies each such cruise' 
;

COMMENT ON COLUMN Manifest.passenger_id IS 'passenger id' 
;

COMMENT ON COLUMN Manifest.cabin_number IS 'The cabins on a given ship are identified by a cabin number' 
;

COMMENT ON COLUMN Manifest.ship_code IS 'a ship code to identify the ship' 
;

COMMENT ON COLUMN Manifest.boarded_datetime IS 'boarded date and time' 
;

ALTER TABLE Manifest 
    ADD CONSTRAINT Manifest_PK PRIMARY KEY ( cruise_id, passenger_id ) ;

CREATE TABLE Operator 
    ( 
     operator_id  NUMBER (30)  NOT NULL , 
     company_name VARCHAR2 (20)  NOT NULL , 
     ceo_name     VARCHAR2 (20)  NOT NULL 
    ) 
;

COMMENT ON COLUMN Operator.operator_id IS 'operator ID as an identifier' 
;

COMMENT ON COLUMN Operator.company_name IS 'company''s name' 
;

COMMENT ON COLUMN Operator.ceo_name IS 'Chief Executive Officer''s name' 
;

ALTER TABLE Operator 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( operator_id ) ;

CREATE TABLE Passenger 
    ( 
     passenger_id  VARCHAR2 (20)  NOT NULL , 
     first_name    VARCHAR2 (15)  NOT NULL , 
     last_name     VARCHAR2 (15)  NOT NULL , 
     date_of_birth DATE  NOT NULL , 
     gender        VARCHAR2 (10)  NOT NULL , 
     P_street      VARCHAR2 (15)  NOT NULL , 
     P_town        VARCHAR2 (15)  NOT NULL , 
     P_postcode    VARCHAR2 (15)  NOT NULL , 
     Country       VARCHAR2 (15)  NOT NULL , 
     phone_number  VARCHAR2 (20) , 
     passenger_id1 VARCHAR2 (20) 
    ) 
;

ALTER TABLE Passenger 
    ADD CONSTRAINT "F/M" 
    CHECK (gender IN ('F', 'M')) 
;

COMMENT ON COLUMN Passenger.passenger_id IS 'passenger id' 
;

COMMENT ON COLUMN Passenger.first_name IS 'passenger first name' 
;

COMMENT ON COLUMN Passenger.last_name IS 'passenger last name' 
;

COMMENT ON COLUMN Passenger.date_of_birth IS 'passengers'' date of birth' 
;

COMMENT ON COLUMN Passenger.gender IS 'passenger gender' 
;

COMMENT ON COLUMN Passenger.P_street IS 'passenger_street' 
;

COMMENT ON COLUMN Passenger.P_town IS 'passenger_town' 
;

COMMENT ON COLUMN Passenger.P_postcode IS 'passenger postcoode' 
;

COMMENT ON COLUMN Passenger.Country IS 'passengers'' country' 
;

COMMENT ON COLUMN Passenger.phone_number IS 'passenger phone number' 
;

COMMENT ON COLUMN Passenger.passenger_id1 IS 'passenger id' 
;

ALTER TABLE Passenger 
    ADD CONSTRAINT Passenger_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE Port 
    ( 
     Port_code      VARCHAR2 (10)  NOT NULL , 
     Port_name      VARCHAR2 (20)  NOT NULL , 
     Port_latitude  NUMBER (10,6)  NOT NULL , 
     Port_longitude NUMBER (10,6)  NOT NULL , 
     Country_code   CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN Port.Port_code IS 'Port code' 
;

COMMENT ON COLUMN Port.Port_name IS 'port name' 
;

COMMENT ON COLUMN Port.Port_latitude IS 'Port latitude' 
;

COMMENT ON COLUMN Port.Port_longitude IS 'Port longtitude' 
;

COMMENT ON COLUMN Port.Country_code IS 'country code' 
;

ALTER TABLE Port 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( Port_code ) ;

CREATE TABLE Ship 
    ( 
     ship_code          NUMBER (20)  NOT NULL , 
     ship_name          VARCHAR2 (30)  NOT NULL , 
     commissioned_date  DATE  NOT NULL , 
     tonnage            NUMBER  NOT NULL , 
     max_guest_capacity NUMBER  NOT NULL , 
     registered_country VARCHAR2 (20)  NOT NULL , 
     operator_id        NUMBER (30)  NOT NULL 
    ) 
;

COMMENT ON COLUMN Ship.ship_code IS 'a ship code to identify the ship' 
;

COMMENT ON COLUMN Ship.ship_name IS 'the ship''s name' 
;

COMMENT ON COLUMN Ship.commissioned_date IS 'the date the ship was commissioned' 
;

COMMENT ON COLUMN Ship.tonnage IS 'tonnage of ship' 
;

COMMENT ON COLUMN Ship.max_guest_capacity IS 'maximum guest capacity of ship' 
;

COMMENT ON COLUMN Ship.registered_country IS 'the name of the country where the ship is registered.' 
;

COMMENT ON COLUMN Ship.operator_id IS 'operator ID as an identifier' 
;

ALTER TABLE Ship 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

CREATE TABLE Visit 
    ( 
     cruise_id        NUMBER (10)  NOT NULL , 
     Port_code        VARCHAR2 (20)  NOT NULL , 
     Datetime         DATE  NOT NULL , 
     DepartureArrival VARCHAR2 (10)  NOT NULL , 
     visit_id         NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE Visit 
    ADD CONSTRAINT D_A 
    CHECK (DepartureArrival IN ('A', 'D')) 
;

COMMENT ON COLUMN Visit.cruise_id IS 'A cruise ID identifies each such cruise' 
;

COMMENT ON COLUMN Visit.Port_code IS 'Port code' 
;

COMMENT ON COLUMN Visit.Datetime IS 'Datetime of visit' 
;

COMMENT ON COLUMN Visit.DepartureArrival IS 'Departure or Arrival' 
;

COMMENT ON COLUMN Visit.visit_id IS 'New Surrogate Key. The primary key field is very long. When referring to (foreign key), three need to be included' 
;

ALTER TABLE Visit 
    ADD CONSTRAINT VISIT_PK PRIMARY KEY ( visit_id ) ;

ALTER TABLE Visit 
    ADD CONSTRAINT Key_2 UNIQUE ( cruise_id , Port_code , Datetime ) ;

ALTER TABLE Manifest 
    ADD CONSTRAINT "Cabin_-_Manifest" FOREIGN KEY 
    ( 
     cabin_number,
     ship_code
    ) 
    REFERENCES Cabin 
    ( 
     cabin_number,
     ship_code
    ) 
;

ALTER TABLE Port 
    ADD CONSTRAINT "Country_-_Port" FOREIGN KEY 
    ( 
     Country_code
    ) 
    REFERENCES Country 
    ( 
     Country_code
    ) 
;

ALTER TABLE Manifest 
    ADD CONSTRAINT "Cruise_-_Manifest" FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES Cruise 
    ( 
     cruise_id
    ) 
;

ALTER TABLE Visit 
    ADD CONSTRAINT "Cruise_-_Visit" FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES Cruise 
    ( 
     cruise_id
    ) 
;

ALTER TABLE Ship 
    ADD CONSTRAINT "Operator_-_Ship" FOREIGN KEY 
    ( 
     operator_id
    ) 
    REFERENCES Operator 
    ( 
     operator_id
    ) 
;

ALTER TABLE Passenger 
    ADD CONSTRAINT "Passenger_-__pas_guardian" FOREIGN KEY 
    ( 
     passenger_id1
    ) 
    REFERENCES Passenger 
    ( 
     passenger_id
    ) 
;

ALTER TABLE Manifest 
    ADD CONSTRAINT "Passenger_-_Manifest" FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES Passenger 
    ( 
     passenger_id
    ) 
;

ALTER TABLE Visit 
    ADD CONSTRAINT "Port_-_Visit" FOREIGN KEY 
    ( 
     Port_code
    ) 
    REFERENCES Port 
    ( 
     Port_code
    ) 
;

ALTER TABLE Cabin 
    ADD CONSTRAINT "Ship_-_Cabin" FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES Ship 
    ( 
     ship_code
    ) 
;

ALTER TABLE Cruise 
    ADD CONSTRAINT "Ship_-_Cruise" FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES Ship 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
